;; Define default fields.
(setq bibtex-BibTeX-entry-alist '(("Article" "Article in Journal"
                                   ("author")
                                   ("date")
                                   ("title" "Title of the article (BibTeX converts it to lowercase)")
                                   ("subtitle" "Title of the article (BibTeX converts it to lowercase)")
                                   ("journaltitle")
                                   ("journalsubtitle")
                                   ("volume" "Volume of the journal")
                                   ("number" "Number of the journal (only allowed if entry contains volume)")
                                   ("issue" "Issue in the journal")
                                   ("pages" "Pages in the journal")
                                   ("url" "Pages in the journal")
                                   ("urldate" "Pages in the journal")
                                   ("doi" "Pages in the journal")
                                   ("library" "Pages in the journal")
                                   ("language" "Pages in the journal")
                                   ("langid" "Pages in the journal")
                                   ("langidopts" "Pages in the journal")
                                   ("file" "Pages in the journal")
                                   ("addendum" "Pages in the journal")
                                   ("keywords"))
                                  ("InProceedings" "Article in Conference Proceedings"
                                   ("author")
                                   ("date")
                                   ("title" "Title of the article (BibTeX converts it to lowercase)")
                                   ("subtitle" "Title of the article (BibTeX converts it to lowercase)")
                                   ("crossref")
                                   ("booktitle" "Name of the conference proceedings")
                                   ("booksubtitle" "Name of the conference proceedings")
                                   ("organization")
                                   ("eventdate")
                                   ("eventtitle")
                                   ("venue")
                                   ("series")
                                   ("volume" "Volume of the conference proceedings in the series")
                                   ("number" "Number of the conference proceedings in a small series (overwritten by volume)")
                                   ("pages" "Pages in the conference proceedings")
                                   ("edition" "Pages in the conference proceedings")
                                   ("publisher" "Publishing company, its location")
                                   ("editor" "Publishing company, its location")
                                   ("translator" "Publishing company, its location")
                                   ("location" "Publishing company, its location")
                                   ("url" "Publishing company, its location")
                                   ("urldate" "Publishing company, its location")
                                   ("doi" "Pages in the journal")
                                   ("library" "Pages in the journal")
                                   ("language" "Pages in the journal")
                                   ("langid" "Pages in the journal")
                                   ("langidopts" "Pages in the journal")
                                   ("file" "Pages in the journal")
                                   ("addendum")
                                   ("keywords"))
                                  ("InCollection" "Article in a Collection"
                                   (("author")
                                    ("title" "Title of the article (BibTeX converts it to lowercase)"))
                                   (("subtitle" "Title of the article (BibTeX converts it to lowercase)")
                                    ("date")
                                    ("crossref" "Title of the article (BibTeX converts it to lowercase)")
                                    ("booktitle" "Name of the conference proceedings")
                                    ("booksubtitle" "Name of the conference proceedings")
                                    ("series")
                                    ("volume" "Volume of the conference proceedings in the series")
                                    ("number" "Number of the conference proceedings in a small series (overwritten by volume)")
                                    ("chapter" "Number of the conference proceedings in a small series (overwritten by volume)")
                                    ("pages" "Pages in the conference proceedings")
                                    ("edition" "Publishing company, its location")
                                    ("publisher" "Publishing company, its location")
                                    ("editor" "Publishing company, its location")
                                    ("translator" "Publishing company, its location")
                                    ("location" "Publishing company, its location")
                                    ("url" "Publishing company, its location")
                                    ("urldate" "Publishing company, its location")
                                    ("doi" "Pages in the journal")
                                    ("library" "Pages in the journal")
                                    ("language" "Pages in the journal")
                                    ("langid" "Pages in the journal")
                                    ("langidopts" "Pages in the journal")
                                    ("file" "Pages in the journal")
                                    ("addendum")
                                    ("keywords")))
                                  ("InBook" "Chapter or Pages in a Book"
                                   (("title" "Title of the article (BibTeX converts it to lowercase)"))
                                   (("author")
                                    ("subtitle" "Title of the article (BibTeX converts it to lowercase)")
                                    ("date")
                                    ("origdate")
                                    ("origtitle")
                                    ("crossref" "Title of the article (BibTeX converts it to lowercase)")
                                    ("booktitle" "Name of the conference proceedings")
                                    ("booksubtitle" "Name of the conference proceedings")
                                    ("series")
                                    ("volume" "Volume of the conference proceedings in the series")
                                    ("number" "Number of the conference proceedings in a small series (overwritten by volume)")
                                    ("chapter" "Number of the conference proceedings in a small series (overwritten by volume)")
                                    ("pages" "Pages in the conference proceedings")
                                    ("edition" "Publishing company, its location")
                                    ("publisher" "Publishing company, its location")
                                    ("editor" "Publishing company, its location")
                                    ("translator" "Publishing company, its location")
                                    ("location" "Publishing company, its location")
                                    ("url" "Publishing company, its location")
                                    ("urldate" "Publishing company, its location")
                                    ("doi" "Pages in the journal")
                                    ("library" "Pages in the journal")
                                    ("language" "Pages in the journal")
                                    ("langid" "Pages in the journal")
                                    ("langidopts" "Pages in the journal")
                                    ("file" "Pages in the journal")
                                    ("addendum")
                                    ("keywords")))
                                  ("Proceedings" "Conference Proceedings"
                                   ("title" "Title of the conference proceedings")
                                   ("date")
                                   nil
                                   ("booktitle" "Title of the proceedings for cross references")
                                   ("editor")
                                   ("volume" "Volume of the conference proceedings in the series")
                                   ("number" "Number of the conference proceedings in a small series (overwritten by volume)")
                                   ("series" "Series in which the conference proceedings appeared")
                                   ("address")
                                   ("month")
                                   ("organization" "Sponsoring organization of the conference")
                                   ("publisher" "Publishing company, its location")
                                   ("note"))
                                  ("Book" "Book"
                                   ("author")
                                   ("date")
                                   ("origdate")
                                   ("origtitle")
                                   ("title" "Title of the article (BibTeX converts it to lowercase)")
                                   ("subtitle" "Title of the article (BibTeX converts it to lowercase)")
                                   ("booktitle" "Name of the conference proceedings")
                                   ("booksubtitle" "Name of the conference proceedings")
                                   ("series")
                                   ("volume" "Volume of the conference proceedings in the series")
                                   ("number" "Number of the conference proceedings in a small series (overwritten by volume)")
                                   ("edition" "Publishing company, its location")
                                   ("publisher" "Publishing company, its location")
                                   ("editor" "Publishing company, its location")
                                   ("translator" "Publishing company, its location")
                                   ("location" "Publishing company, its location")
                                   ("url" "Publishing company, its location")
                                   ("urldate" "Publishing company, its location")
                                   ("doi" "Pages in the journal")
                                   ("library" "Pages in the journal")
                                   ("isbn" "Pages in the journal")
                                   ("origlanguage" "Pages in the journal")
                                   ("language" "Pages in the journal")
                                   ("langid" "Pages in the journal")
                                   ("langidopts" "Pages in the journal")
                                   ("file" "Pages in the journal")
                                   ("addendum")
                                   ("keywords"))
                                  ("Unpublished" "Unpublished"
                                   ("author")
                                   ("date")
                                   ("title" "Title of the article (BibTeX converts it to lowercase)")
                                   ("subtitle" "Title of the article (BibTeX converts it to lowercase)")
                                   ("type" "Title of the article (BibTeX converts it to lowercase)")
                                   ("eventdate" "Title of the article (BibTeX converts it to lowercase)")
                                   ("eventtitle" "Title of the article (BibTeX converts it to lowercase)")
                                   ("venue" "Title of the article (BibTeX converts it to lowercase)")
                                   ("location" "Title of the article (BibTeX converts it to lowercase)")
                                   ("url" "Publishing company, its location")
                                   ("urldate" "Publishing company, its location")
                                   ("doi" "Pages in the journal")
                                   ("library" "Pages in the journal")
                                   ("origlanguage" "Pages in the journal")
                                   ("language" "Pages in the journal")
                                   ("langid" "Pages in the journal")
                                   ("langidopts" "Pages in the journal")
                                   ("file" "Pages in the journal")
                                   ("addendum")
                                   ("keywords"))
                                  ("Misc" "Miscellaneous" nil nil
                                   (("title" "Title of the article (BibTeX converts it to lowercase)"))
                                   (("author")
                                    ("date")
                                    ("subtitle" "Title of the article (BibTeX converts it to lowercase)")
                                    ("organization" "Title of the article (BibTeX converts it to lowercase)")
                                    ("type" "Title of the article (BibTeX converts it to lowercase)")
                                    ("version" "Title of the article (BibTeX converts it to lowercase)")
                                    ("location" "Title of the article (BibTeX converts it to lowercase)")
                                    ("url" "Publishing company, its location")
                                    ("urldate" "Publishing company, its location")
                                    ("doi" "Pages in the journal")
                                    ("library" "Pages in the journal")
                                    ("origlanguage" "Pages in the journal")
                                    ("language" "Pages in the journal")
                                    ("langid" "Pages in the journal")
                                    ("langidopts" "Pages in the journal")
                                    ("file" "Pages in the journal")
                                    ("addendum")
                                    ("keywords")))))

(setq bibtex-biblatex-entry-alist '(("Article" "Article in Journal"
                                     (("author")
                                      ("title")
                                      ("journaltitle")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     nil
                                     (("translator")
                                      ("annotator")
                                      ("commentator")
                                      ("subtitle")
                                      ("titleaddon")
                                      ("editor")
                                      ("editora")
                                      ("editorb")
                                      ("editorc")
                                      ("journalsubtitle")
                                      ("issuetitle")
                                      ("issuesubtitle")
                                      ("language")
                                      ("origlanguage")
                                      ("series")
                                      ("volume")
                                      ("number")
                                      ("eid")
                                      ("issue")
                                      ("month")
                                      ("pages")
                                      ("version")
                                      ("note")
                                      ("issn")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("Book" "Single-Volume Book"
                                     (("author")
                                      ("title")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     nil
                                     (("editor")
                                      ("editora")
                                      ("editorb")
                                      ("editorc")
                                      ("translator")
                                      ("annotator")
                                      ("commentator")
                                      ("introduction")
                                      ("foreword")
                                      ("afterword")
                                      ("subtitle")
                                      ("titleaddon")
                                      ("maintitle")
                                      ("mainsubtitle")
                                      ("maintitleaddon")
                                      ("language")
                                      ("origlanguage")
                                      ("volume")
                                      ("part")
                                      ("edition")
                                      ("volumes")
                                      ("series")
                                      ("number")
                                      ("note")
                                      ("publisher")
                                      ("location")
                                      ("isbn")
                                      ("chapter")
                                      ("pages")
                                      ("pagetotal")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("MVBook" "Multi-Volume Book"
                                     (("author")
                                      ("title")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     nil
                                     (("editor")
                                      ("editora")
                                      ("editorb")
                                      ("editorc")
                                      ("translator")
                                      ("annotator")
                                      ("commentator")
                                      ("introduction")
                                      ("foreword")
                                      ("afterword")
                                      ("subtitle")
                                      ("titleaddon")
                                      ("language")
                                      ("origlanguage")
                                      ("edition")
                                      ("volumes")
                                      ("series")
                                      ("number")
                                      ("note")
                                      ("publisher")
                                      ("location")
                                      ("isbn")
                                      ("pagetotal")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("InBook" "Chapter or Pages in a Book"
                                     (("title")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     (("author")
                                      ("booktitle"))
                                     (("bookauthor")
                                      ("editor")
                                      ("editora")
                                      ("editorb")
                                      ("editorc")
                                      ("translator")
                                      ("annotator")
                                      ("commentator")
                                      ("introduction")
                                      ("foreword")
                                      ("afterword")
                                      ("subtitle")
                                      ("titleaddon")
                                      ("maintitle")
                                      ("mainsubtitle")
                                      ("maintitleaddon")
                                      ("booksubtitle")
                                      ("booktitleaddon")
                                      ("language")
                                      ("origlanguage")
                                      ("volume")
                                      ("part")
                                      ("edition")
                                      ("volumes")
                                      ("series")
                                      ("number")
                                      ("note")
                                      ("publisher")
                                      ("location")
                                      ("isbn")
                                      ("chapter")
                                      ("pages")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("BookInBook" "Book in Collection"
                                     (("title")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     (("author")
                                      ("booktitle"))
                                     (("bookauthor")
                                      ("editor")
                                      ("editora")
                                      ("editorb")
                                      ("editorc")
                                      ("translator")
                                      ("annotator")
                                      ("commentator")
                                      ("introduction")
                                      ("foreword")
                                      ("afterword")
                                      ("subtitle")
                                      ("titleaddon")
                                      ("maintitle")
                                      ("mainsubtitle")
                                      ("maintitleaddon")
                                      ("booksubtitle")
                                      ("booktitleaddon")
                                      ("language")
                                      ("origlanguage")
                                      ("volume")
                                      ("part")
                                      ("edition")
                                      ("volumes")
                                      ("series")
                                      ("number")
                                      ("note")
                                      ("publisher")
                                      ("location")
                                      ("isbn")
                                      ("chapter")
                                      ("pages")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("SuppBook" "Supplemental Material in a Book"
                                     (("title")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     (("author")
                                      ("booktitle"))
                                     (("bookauthor")
                                      ("editor")
                                      ("editora")
                                      ("editorb")
                                      ("editorc")
                                      ("translator")
                                      ("annotator")
                                      ("commentator")
                                      ("introduction")
                                      ("foreword")
                                      ("afterword")
                                      ("subtitle")
                                      ("titleaddon")
                                      ("maintitle")
                                      ("mainsubtitle")
                                      ("maintitleaddon")
                                      ("booksubtitle")
                                      ("booktitleaddon")
                                      ("language")
                                      ("origlanguage")
                                      ("volume")
                                      ("part")
                                      ("edition")
                                      ("volumes")
                                      ("series")
                                      ("number")
                                      ("note")
                                      ("publisher")
                                      ("location")
                                      ("isbn")
                                      ("chapter")
                                      ("pages")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("Booklet" "Booklet (Bound, but no Publisher)"
                                     (("author" nil nil 0)
                                      ("editor" nil nil 0)
                                      ("title")
                                      ;; ("year" nil nil 1)
                                      ("date" nil nil 1))
                                     nil
                                     (("subtitle")
                                      ("titleaddon")
                                      ("language")
                                      ("howpublished")
                                      ("type")
                                      ("note")
                                      ("location")
                                      ("chapter")
                                      ("pages")
                                      ("pagetotal")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("Collection" "Single-Volume Collection"
                                     (("editor")
                                      ("title")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     nil
                                     (("editora")
                                      ("editorb")
                                      ("editorc")
                                      ("translator")
                                      ("annotator")
                                      ("commentator")
                                      ("introduction")
                                      ("foreword")
                                      ("afterword")
                                      ("subtitle")
                                      ("titleaddon")
                                      ("maintitle")
                                      ("mainsubtitle")
                                      ("maintitleaddon")
                                      ("language")
                                      ("origlanguage")
                                      ("volume")
                                      ("part")
                                      ("edition")
                                      ("volumes")
                                      ("series")
                                      ("number")
                                      ("note")
                                      ("publisher")
                                      ("location")
                                      ("isbn")
                                      ("chapter")
                                      ("pages")
                                      ("pagetotal")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("MVCollection" "Multi-Volume Collection"
                                     (("editor")
                                      ("title")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     nil
                                     (("editora")
                                      ("editorb")
                                      ("editorc")
                                      ("translator")
                                      ("annotator")
                                      ("commentator")
                                      ("introduction")
                                      ("foreword")
                                      ("afterword")
                                      ("subtitle")
                                      ("titleaddon")
                                      ("language")
                                      ("origlanguage")
                                      ("edition")
                                      ("volumes")
                                      ("series")
                                      ("number")
                                      ("note")
                                      ("publisher")
                                      ("location")
                                      ("isbn")
                                      ("pagetotal")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("InCollection" "Article in a Collection"
                                     (("author")
                                      ("title")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     (("booktitle"))
                                     (("editor")
                                      ("editora")
                                      ("editorb")
                                      ("editorc")
                                      ("translator")
                                      ("annotator")
                                      ("commentator")
                                      ("introduction")
                                      ("foreword")
                                      ("afterword")
                                      ("subtitle")
                                      ("titleaddon")
                                      ("maintitle")
                                      ("mainsubtitle")
                                      ("maintitleaddon")
                                      ("booksubtitle")
                                      ("booktitleaddon")
                                      ("language")
                                      ("origlanguage")
                                      ("volume")
                                      ("part")
                                      ("edition")
                                      ("volumes")
                                      ("series")
                                      ("number")
                                      ("note")
                                      ("publisher")
                                      ("location")
                                      ("isbn")
                                      ("chapter")
                                      ("pages")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("SuppCollection" "Supplemental Material in a Collection"
                                     (("author")
                                      ("editor")
                                      ("title")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     (("booktitle"))
                                     (("editora")
                                      ("editorb")
                                      ("editorc")
                                      ("translator")
                                      ("annotator")
                                      ("commentator")
                                      ("introduction")
                                      ("foreword")
                                      ("afterword")
                                      ("subtitle")
                                      ("titleaddon")
                                      ("maintitle")
                                      ("mainsubtitle")
                                      ("maintitleaddon")
                                      ("booksubtitle")
                                      ("booktitleaddon")
                                      ("language")
                                      ("origlanguage")
                                      ("volume")
                                      ("part")
                                      ("edition")
                                      ("volumes")
                                      ("series")
                                      ("number")
                                      ("note")
                                      ("publisher")
                                      ("location")
                                      ("isbn")
                                      ("chapter")
                                      ("pages")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("Manual" "Technical Manual"
                                     (("author" nil nil 0)
                                      ("editor" nil nil 0)
                                      ("title")
                                      ;; ("year" nil nil 1)
                                      ("date" nil nil 1))
                                     nil
                                     (("subtitle")
                                      ("titleaddon")
                                      ("language")
                                      ("edition")
                                      ("type")
                                      ("series")
                                      ("number")
                                      ("version")
                                      ("note")
                                      ("organization")
                                      ("publisher")
                                      ("location")
                                      ("isbn")
                                      ("chapter")
                                      ("pages")
                                      ("pagetotal")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("Misc" "Miscellaneous"
                                     (("author" nil nil 0)
                                      ("editor" nil nil 0)
                                      ("title")
                                      ;; ("year" nil nil 1)
                                      ("date" nil nil 1))
                                     nil
                                     (("subtitle")
                                      ("titleaddon")
                                      ("language")
                                      ("howpublished")
                                      ("type")
                                      ("version")
                                      ("note")
                                      ("organization")
                                      ("location")
                                      ("date")
                                      ("month")
                                      ("year")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("Online" "Online Resource"
                                     (("author" nil nil 0)
                                      ("editor" nil nil 0)
                                      ("title")
                                      ;; ("year" nil nil 1)
                                      ("date" nil nil 1)
                                      ("url"))
                                     nil
                                     (("subtitle")
                                      ("titleaddon")
                                      ("language")
                                      ("version")
                                      ("note")
                                      ("organization")
                                      ("date")
                                      ("month")
                                      ("year")
                                      ("addendum")
                                      ("pubstate")
                                      ("urldate")))
                                    ("Patent" "Patent"
                                     (("author")
                                      ("title")
                                      ("number")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     nil
                                     (("holder")
                                      ("subtitle")
                                      ("titleaddon")
                                      ("type")
                                      ("version")
                                      ("location")
                                      ("note")
                                      ("date")
                                      ("month")
                                      ("year")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("Periodical" "Complete Issue of a Periodical"
                                     (("editor")
                                      ("title")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     nil
                                     (("editora")
                                      ("editorb")
                                      ("editorc")
                                      ("subtitle")
                                      ("issuetitle")
                                      ("issuesubtitle")
                                      ("language")
                                      ("series")
                                      ("volume")
                                      ("number")
                                      ("issue")
                                      ("date")
                                      ("month")
                                      ("year")
                                      ("note")
                                      ("issn")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("SuppPeriodical" "Supplemental Material in a Periodical"
                                     (("author")
                                      ("title")
                                      ("journaltitle")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     nil
                                     (("translator")
                                      ("annotator")
                                      ("commentator")
                                      ("subtitle")
                                      ("titleaddon")
                                      ("editor")
                                      ("editora")
                                      ("editorb")
                                      ("editorc")
                                      ("journalsubtitle")
                                      ("issuetitle")
                                      ("issuesubtitle")
                                      ("language")
                                      ("origlanguage")
                                      ("series")
                                      ("volume")
                                      ("number")
                                      ("eid")
                                      ("issue")
                                      ("month")
                                      ("pages")
                                      ("version")
                                      ("note")
                                      ("issn")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("Proceedings" "Single-Volume Conference Proceedings"
                                     (("title")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     nil
                                     (("subtitle")
                                      ("titleaddon")
                                      ("maintitle")
                                      ("mainsubtitle")
                                      ("maintitleaddon")
                                      ("eventtitle")
                                      ("eventdate")
                                      ("venue")
                                      ("language")
                                      ("editor")
                                      ("volume")
                                      ("part")
                                      ("volumes")
                                      ("series")
                                      ("number")
                                      ("note")
                                      ("organization")
                                      ("publisher")
                                      ("location")
                                      ("month")
                                      ("isbn")
                                      ("chapter")
                                      ("pages")
                                      ("pagetotal")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("MVProceedings" "Multi-Volume Conference Proceedings"
                                     (("editor")
                                      ("title")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     nil
                                     (("subtitle")
                                      ("titleaddon")
                                      ("eventtitle")
                                      ("eventdate")
                                      ("venue")
                                      ("language")
                                      ("volumes")
                                      ("series")
                                      ("number")
                                      ("note")
                                      ("organization")
                                      ("publisher")
                                      ("location")
                                      ("month")
                                      ("isbn")
                                      ("pagetotal")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("InProceedings" "Article in Conference Proceedings"
                                     (("author")
                                      ("title")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     (("booktitle"))
                                     (("editor")
                                      ("subtitle")
                                      ("titleaddon")
                                      ("maintitle")
                                      ("mainsubtitle")
                                      ("maintitleaddon")
                                      ("booksubtitle")
                                      ("booktitleaddon")
                                      ("eventtitle")
                                      ("eventdate")
                                      ("venue")
                                      ("language")
                                      ("volume")
                                      ("part")
                                      ("volumes")
                                      ("series")
                                      ("number")
                                      ("note")
                                      ("organization")
                                      ("publisher")
                                      ("location")
                                      ("month")
                                      ("isbn")
                                      ("chapter")
                                      ("pages")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("Reference" "Single-Volume Work of Reference"
                                     (("editor")
                                      ("title")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     nil
                                     (("editora")
                                      ("editorb")
                                      ("editorc")
                                      ("translator")
                                      ("annotator")
                                      ("commentator")
                                      ("introduction")
                                      ("foreword")
                                      ("afterword")
                                      ("subtitle")
                                      ("titleaddon")
                                      ("maintitle")
                                      ("mainsubtitle")
                                      ("maintitleaddon")
                                      ("language")
                                      ("origlanguage")
                                      ("volume")
                                      ("part")
                                      ("edition")
                                      ("volumes")
                                      ("series")
                                      ("number")
                                      ("note")
                                      ("publisher")
                                      ("location")
                                      ("isbn")
                                      ("chapter")
                                      ("pages")
                                      ("pagetotal")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("MVReference" "Multi-Volume Work of Reference"
                                     (("editor")
                                      ("title")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     nil
                                     (("editora")
                                      ("editorb")
                                      ("editorc")
                                      ("translator")
                                      ("annotator")
                                      ("commentator")
                                      ("introduction")
                                      ("foreword")
                                      ("afterword")
                                      ("subtitle")
                                      ("titleaddon")
                                      ("language")
                                      ("origlanguage")
                                      ("edition")
                                      ("volumes")
                                      ("series")
                                      ("number")
                                      ("note")
                                      ("publisher")
                                      ("location")
                                      ("isbn")
                                      ("pagetotal")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("InReference" "Article in a Work of Reference"
                                     (("author")
                                      ("editor")
                                      ("title")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     (("booktitle"))
                                     (("editora")
                                      ("editorb")
                                      ("editorc")
                                      ("translator")
                                      ("annotator")
                                      ("commentator")
                                      ("introduction")
                                      ("foreword")
                                      ("afterword")
                                      ("subtitle")
                                      ("titleaddon")
                                      ("maintitle")
                                      ("mainsubtitle")
                                      ("maintitleaddon")
                                      ("booksubtitle")
                                      ("booktitleaddon")
                                      ("language")
                                      ("origlanguage")
                                      ("volume")
                                      ("part")
                                      ("edition")
                                      ("volumes")
                                      ("series")
                                      ("number")
                                      ("note")
                                      ("publisher")
                                      ("location")
                                      ("isbn")
                                      ("chapter")
                                      ("pages")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("Report" "Technical or Research Report"
                                     (("author")
                                      ("title")
                                      ("type")
                                      ("institution")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     nil
                                     (("subtitle")
                                      ("titleaddon")
                                      ("language")
                                      ("number")
                                      ("version")
                                      ("note")
                                      ("location")
                                      ("month")
                                      ("isrn")
                                      ("chapter")
                                      ("pages")
                                      ("pagetotal")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("Thesis" "PhD. or Master's Thesis"
                                     (("author")
                                      ("title")
                                      ("type")
                                      ("institution")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     nil
                                     (("subtitle")
                                      ("titleaddon")
                                      ("language")
                                      ("note")
                                      ("location")
                                      ("month")
                                      ("isbn")
                                      ("chapter")
                                      ("pages")
                                      ("pagetotal")
                                      ("addendum")
                                      ("pubstate")
                                      ("doi")
                                      ("eprint")
                                      ("eprintclass")
                                      ("eprinttype")
                                      ("url")
                                      ("urldate")))
                                    ("Unpublished" "Unpublished"
                                     (("author")
                                      ("title")
                                      ;; ("year" nil nil 0)
                                      ("date" nil nil 0))
                                     nil
                                     (("subtitle")
                                      ("titleaddon")
                                      ("language")
                                      ("howpublished")
                                      ("note")
                                      ("location")
                                      ("isbn")
                                      ("date")
                                      ("month")
                                      ("year")
                                      ("addendum")
                                      ("pubstate")
                                      ("url")
                                      ("urldate")))))

(provide 'sync0-bibtex-fields)
