(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(company-auto-commit nil nil nil "Customized with use-package company")
 '(fringe-mode 0 nil (fringe))
 '(scihub-homepage "https://sci-hub.ee"))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(markdown-code-face ((t (:family "Inconsolata" :height 1.0 :spacing monospace :inherit fixed-pitch))))
 '(markdown-footnote-marker-face ((t (:family "Sitka Text" :style small :weight bold :height 0.7))))
 '(markdown-gfm-checkbox-face ((t (:family "Inconsolata" :weight bold :spacing monospace))))
 '(markdown-header-face ((t (:family "Helvetica Neue LT Std" :weight light :width condensed :background nil :inherit variable-pitch))))
 '(markdown-link-face ((t (:family "Sitka Text" :underline t :background nil :height 1.0 :inherit variable-pitch))))
 '(markdown-markup-face ((t (:family "Sitka Text" :underline nil :background nil :height 1.0 :inherit variable-pitch))))
 '(markdown-metadata-key-face ((t (:family "Inconsolata" :weight bold :height 0.9 :slant normal :spacing monospace :background nil :inherit fixed-pitch))))
 '(markdown-metadata-value-face ((t (:family "Inconsolata" :height 0.9 :slant normal :spacing monospace :inherit fixed-pitch))))
 '(markdown-plain-url-face ((t (:inherit markdown-url-face))))
 '(markdown-reference-face ((t (:inherit markdown-code-face))))
 '(markdown-url-face ((t (:family "Sitka Text" :underline nil :background nil :height 1.0 :inherit variable-pitch))))
 '(org-agenda-date ((t (:family "Helvetica Neue LT Std" :height 1.563 :weight light :width condensed :inherit variable-pitch))))
 '(org-agenda-date-today ((t (:family "Helvetica Neue LT Std" :height 1.563 :weight light :width condensed :inherit variable-pitch))))
 '(org-agenda-date-weekend ((t (:family "Helvetica Neue LT Std" :height 1.563 :weight light :width condensed :inherit variable-pitch))))
 '(org-agenda-diary ((t (:family "Inconsolata" :spacing monospace :inherit fixed-pitch))))
 '(org-agenda-done ((t (:strike-through t))))
 '(org-agenda-structure ((t (:family "Helvetica Neue LT Std" :height 1.953 :weight light :width condensed :inherit variable-pitch))))
 '(org-block ((t (:family "Inconsolata" :height 0.95 :spacing monospace :background nil :inherit fixed-pitch))))
 '(org-block-begin-line ((t (:family "Inconsolata" :height 0.95 :spacing monospace :weight bold :inherit fixed-pitch))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-checkbox ((t (:family "Inconsolata" :weight bold :spacing monospace))))
 '(org-date ((t (:family "Inconsolata" :height 0.95 :spacing monospace :inherit fixed-pitch))))
 '(org-default ((t (:family "Sitka Text" :inherit variable-pitch))))
 '(org-document-info ((t (:family "Helvetica Neue LT Std" :height 1.728 :weight light :width condensed :inherit variable-pitch))))
 '(org-document-info-keyword ((t (:inherit org-meta-line))))
 '(org-document-title ((t (:family "Helvetica Neue LT Std" :height 2.074 :weight light :width condensed :inherit variable-pitch))))
 '(org-drawer ((t (:inherit org-meta-line))))
 '(org-ellipsis ((t (:family "Fira Code" :underline nil :box nil))))
 '(org-footnote ((t (:family "Sitka Text" :style small :weight bold :height 0.7))))
 '(org-level-1 ((t (:family "Helvetica Neue LT Std" :height 2.074 :weight light :width condensed :inherit variable-pitch))))
 '(org-level-2 ((t (:family "Helvetica Neue LT Std" :height 1.728 :weight light :width condensed :inherit variable-pitch))))
 '(org-level-3 ((t (:family "Helvetica Neue LT Std" :height 1.44 :weight light :width condensed :inherit variable-pitch))))
 '(org-level-4 ((t (:family "Helvetica Neue LT Std" :height 1.2 :weight medium :width condensed :inherit variable-pitch))))
 '(org-level-5 ((t (:family "Helvetica Neue LT Std" :height 1.0 :weight medium :width condensed :inherit variable-pitch))))
 '(org-level-6 ((t (:family "Helvetica Neue LT Std" :height 0.833 :weight medium :width condensed :inherit variable-pitch))))
 '(org-link ((t (:inherit org-default :underline t))))
 '(org-meta-line ((t (:family "Inconsolata" :height 0.95 :slant normal :spacing monospace :inherit fixed-pitch))))
 '(org-property-value ((t (:inherit org-meta-line))) t)
 '(org-ref-cite-face ((t (:inherit org-link))))
 '(org-scheduled ((t (:weight medium :slant normal))))
 '(org-scheduled-previously ((t (:family "Inconsolata" :weight normal :slant normal :spacing monospace :inherit fixed-pitch))))
 '(org-scheduled-today ((t (:family "Inconsolata" :weight medium :slant normal :spacing monospace :inherit fixed-pitch))))
 '(org-special-keywords ((t (:inherit org-meta-line))))
 '(org-table ((t (:family "Inconsolata" :height 0.95 :spacing monospace :inherit fixed-pitch))))
 '(org-tag ((t (:family "Inconsolata" :height 0.75 :spacing monospace :inherit fixed-pitch))))
 '(org-upcoming-deadline ((t (:inherit org-scheduled-previously)))))
